"""empty message

Revision ID: 462da8d726a4
Revises: 30eb34ec9f29
Create Date: 2022-03-07 22:30:33.358172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '462da8d726a4'
down_revision = '30eb34ec9f29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue_genres',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('genere_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genere_id'], ['genere.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'genere_id')
    )
    op.add_column('venue', sa.Column('website_link', sa.String(length=500), nullable=True))
    op.add_column('venue', sa.Column('looking_for_talent', sa.Boolean(), nullable=True))
    op.add_column('venue', sa.Column('seeking_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_description')
    op.drop_column('venue', 'looking_for_talent')
    op.drop_column('venue', 'website_link')
    op.drop_table('venue_genres')
    op.drop_table('show')
    # ### end Alembic commands ###
