"""empty message

Revision ID: 9e6df0fba44f
Revises: 0082145ae9d3
Create Date: 2022-03-03 23:01:43.527542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e6df0fba44f'
down_revision = '0082145ae9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artist_genres',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('genere_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], ),
    sa.ForeignKeyConstraint(['genere_id'], ['Genre.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'genere_id')
    )
    op.drop_table('Genres')
    op.drop_column('Artist', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_table('Genres',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Genres_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('genere_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['genere_id'], ['Artist.id'], name='Genres_genere_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Genres_pkey')
    )
    op.drop_table('artist_genres')
    op.drop_table('Genre')
    # ### end Alembic commands ###
