"""empty message

Revision ID: a4462d456fbc
Revises: bea3896a9edc
Create Date: 2022-03-03 23:30:14.043303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4462d456fbc'
down_revision = 'bea3896a9edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'artist_genres', 'artist', ['artist_id'], ['id'])
    op.create_foreign_key(None, 'artist_genres', 'genere', ['genere_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artist_genres', type_='foreignkey')
    op.drop_constraint(None, 'artist_genres', type_='foreignkey')
    # ### end Alembic commands ###
